{% set name = "turbodbc" %}
{% set version = "4.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9132140d6c7f0bf8bfd68be4dd3b2a92a4268d31c66932c87fe3cbc94d33935d

build:
  number: 1
  skip: true  # [py<39]
  # turbodbc already has set the correct RPATHs, conda relocation breaks it
  # so skip it.
  binary_relocation: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libarrow                               # [build_platform != target_platform]
    - pyarrow                                # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - libboost-headers
    - numpy
    - pybind11
    - python
    - setuptools
    - six
    - unixodbc  # [unix]
    - libarrow
    - pyarrow
  run:
    - python
    # pkg_resources is used to determine the package version
    - setuptools
    - six
    - {{ pin_compatible('numpy') }}
    - unixodbc  # [unix]
    - pyarrow

test:
  requires:
    - pip
  imports:
    - turbodbc
    - turbodbc.arrow_support
  commands:
    # We need to remove pybind11 from the runtime dependencies for this to suceed. 
    # - pip check

about:
  home: https://github.com/blue-yonder/turbodbc
  license: MIT
  license_file: LICENSE
  summary: access relational databases via the Open Database Connectivity (ODBC) interface
  description: |
    Turbodbc is a Python module to access relational databases via the Open
    Database Connectivity (ODBC) interface. In addition to complying with the
    Python Database API Specification 2.0, turbodbc offers built-in NumPy and
    Apache Arrow support. Don't wait minutes for your results, just blink.

extra:
  recipe-maintainers:
    - ldacey
    - MathMagique
    - xhochy
    - wesm
    - fjetter
