{% set name = "turbodbc" %}
{% set version = "5.0.2" %}

# appease linter
{% if libarrow is undefined %}
{% set libarrow = "18" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 863d00abae5f6fee4a7c9a2e4339f838ab978ffd9bd5195abe28d69eab3e85a5

build:
  number: 2
  skip: true  # [py<310]
  skip: true  # [libarrow==14]
  # turbodbc already has set the correct RPATHs, conda relocation breaks it
  # so skip it.
  binary_relocation: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libarrow                               # [build_platform != target_platform]
    - pyarrow                                # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - sed                                    # [build_platform != target_platform]
    - cmake
    - pkg-config
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - libboost-headers
    - numpy
    - pybind11
    - python
    - python-build
    - six
    - unixodbc  # [unix]
    - libarrow
    - pyarrow
    - simdutf
    - meson-python
  run:
    - python
    # pkg_resources is used to determine the package version
    - setuptools
    - six
    - unixodbc  # [unix]
    - pyarrow

test:
  requires:
    - pip
  imports:
    - turbodbc
  commands:
    - pip check
    - echo "{{ libarrow }}"

about:
  home: https://github.com/blue-yonder/turbodbc
  license: MIT
  license_file: LICENSE
  summary: access relational databases via the Open Database Connectivity (ODBC) interface
  description: |
    Turbodbc is a Python module to access relational databases via the Open
    Database Connectivity (ODBC) interface. In addition to complying with the
    Python Database API Specification 2.0, turbodbc offers built-in NumPy and
    Apache Arrow support. Don't wait minutes for your results, just blink.

extra:
  recipe-maintainers:
    - ldacey
    - MathMagique
    - xhochy
    - wesm
    - fjetter
