{% set name = "turbodbc" %}
{% set version = "3.3.0" %}
{% set sha256 = "4e1fce94926f756bfec9d2dcc54d4187fad60ac352617ed805c6356ee7ae0ece" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  # turbodbc already has set the correct RPATHs, conda relocation breaks it
  # so skip it.
  binary_relocation: False
  skip: true  # [win32]
  skip: true  # [win and py<35]
  # Python 3.8 fails due to linking errors
  skip: true  # [win and py==38]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - boost-cpp
    - numpy 1.16.*
    - pybind11
    - python
    - setuptools
    - six
    - unixodbc  # [unix]
    - arrow-cpp
    - pyarrow
  run:
    - python
    # pkg_resources is used to determine the package version
    - setuptools
    - six
    - {{ pin_compatible('numpy', lower_bound='1.16') }}
    - unixodbc  # [unix]
    - pyarrow

test:
  imports:
    - turbodbc
    - turbodbc_arrow_support
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [linux]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/blue-yonder/turbodbc
  license: MIT
  license_file: LICENSE
  summary: 'access relational databases via the Open Database Connectivity (ODBC) interface'
  description: |
    Turbodbc is a Python module to access relational databases via the Open
    Database Connectivity (ODBC) interface. In addition to complying with the
    Python Database API Specification 2.0, turbodbc offers built-in NumPy and
    Apache Arrow support. Don't wait minutes for your results, just blink.

extra:
  recipe-maintainers:
    - MathMagique
    - xhochy
    - wesm
    - fjetter
