{% set name = "turbodbc" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68c03b41cc4bd845d189130d7c92c103b63bf587dc02783fea788b062fab6f6c

build:
  number: 5
  # turbodbc already has set the correct RPATHs, conda relocation breaks it
  # so skip it.
  binary_relocation: false
  # Python 3.8+ fails due to linking errors
  skip: true  # [win and py>=38]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - boost-cpp
    - numpy
    - pybind11
    - python
    - setuptools
    - six
    - unixodbc  # [unix]
    - arrow-cpp
    - pyarrow
  run:
    - python
    # pkg_resources is used to determine the package version
    - setuptools
    - six
    - {{ pin_compatible('numpy') }}
    - unixodbc  # [unix]
    - pyarrow

test:
  requires:
    - pip
  imports:
    - turbodbc
    - turbodbc_arrow_support
  commands:
    # We need to remove pybind11 from the runtime dependencies for this to suceed. 
    # - pip check
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [linux]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/blue-yonder/turbodbc
  license: MIT
  license_file: LICENSE
  summary: access relational databases via the Open Database Connectivity (ODBC) interface
  description: |
    Turbodbc is a Python module to access relational databases via the Open
    Database Connectivity (ODBC) interface. In addition to complying with the
    Python Database API Specification 2.0, turbodbc offers built-in NumPy and
    Apache Arrow support. Don't wait minutes for your results, just blink.

extra:
  recipe-maintainers:
    - MathMagique
    - xhochy
    - wesm
    - fjetter
