# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Yh+Q55bM66f/1QZ9ZfSZaFPyl8AgmWd8PVtZDLJoHwqVTJ5Je1G3maewyHkUXDWRCZ39mTdufFuiyTiSFtggl3OFlMUInYlhvDlnhrL7EUOmGqbJFDKjo6JL8pruZnm7eYuC436EHoVI9iax2EBtwcljX7PCgw66tib1Y6Y39PngAf8+6I9gzsiJM8vuLyyx4fegs24UupkvVkkwGQCUKjqYc6KpJhi2kN8Nl62BOst1cn4YVKGTz08tpOF0II5FBn3vh6abbvqiMApOEcPGTFNE/osQwz5PLgxOihosFN/bMryYxtD2RRXbROaPUiSnyPkRJITabEDObAMSqXeb2UZ8V1iFhKv9OF49UgnncwhaqrT7ShegamckH6i4/9tgc9RsQTYyz002meJT0Rzq7EsiW7SHZicQCYQ0ecPjwWzqDjiKJHoWdlsNmP7Ez8+u7D1RbDFA5gb1UUC++raZFAuy1gJGinXAcKlAMosBXMs1YECBL4XyEZi1BvZKtiqa1c7ed/y07TvF+rf7EgBsOwAh1wH6mQPeP9nf5LKR5+EgJ/vg736Snwf8XhK8MQ9sGsXK/8Ki/ZgKE0Z8U+3kfaS5kJFc0aT75TfC5BR++GCOy8yxNFeH/5NbRWnWjCQDnf+INarnakAs9xvx3T9RCiZRKopAoI9EOOHOF0KejPA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
