appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Yh+Q55bM66f/1QZ9ZfSZaFPyl8AgmWd8PVtZDLJoHwqVTJ5Je1G3maewyHkUXDWRCZ39mTdufFuiyTiSFtggl3OFlMUInYlhvDlnhrL7EUOmGqbJFDKjo6JL8pruZnm7eYuC436EHoVI9iax2EBtwcljX7PCgw66tib1Y6Y39PngAf8+6I9gzsiJM8vuLyyx4fegs24UupkvVkkwGQCUKjqYc6KpJhi2kN8Nl62BOst1cn4YVKGTz08tpOF0II5FBn3vh6abbvqiMApOEcPGTFNE/osQwz5PLgxOihosFN/bMryYxtD2RRXbROaPUiSnyPkRJITabEDObAMSqXeb2UZ8V1iFhKv9OF49UgnncwhaqrT7ShegamckH6i4/9tgc9RsQTYyz002meJT0Rzq7EsiW7SHZicQCYQ0ecPjwWzqDjiKJHoWdlsNmP7Ez8+u7D1RbDFA5gb1UUC++raZFAuy1gJGinXAcKlAMosBXMs1YECBL4XyEZi1BvZKtiqa1c7ed/y07TvF+rf7EgBsOwAh1wH6mQPeP9nf5LKR5+EgJ/vg736Snwf8XhK8MQ9sGsXK/8Ki/ZgKE0Z8U+3kfaS5kJFc0aT75TfC5BR++GCOy8yxNFeH/5NbRWnWjCQDnf+INarnakAs9xvx3T9RCiZRKopAoI9EOOHOF0KejPA=}
provider:
  win: azure
conda_forge_output_validation: false
